### ISSUE TITLE
updater.progress(progress) value error.

### ISSUE THREAD

**Issue by TKNgu** [AppImage/AppImageUpdate#103]
I have simple code.
```
#include <iostream>
#include <string>
#include <chrono>
#include <thread>
#include "appimage/update.h"

int main(int argc, char** argv) {
    std::cout << "Hello OK" << std::endl;
    if(argc < 2) {
        std::cout << "Not path file" << std::endl;
        return 0;
    }
    appimage::update::Updater updater(std::string(argv[1]), false);
    if(!updater.start()) {
        std::cout << "Error" << std::endl;
        return 0;
    }
    std::cout << "Start" << std::endl;
    double progress;
    double last = -1;
    while(!updater.isDone()) {
        if(!updater.progress(progress)) {
            return 0;
        }
        if(progress != last) {
            std::cout << (progress * 100.0f) << std::endl;
            last = progress;
        }
        std::this_thread::sleep_for(std::chrono::milliseconds((int)(1000.0f / 1.0f))); //small sleep time.
    }
    return 0;
}
```
Run ok but value ``` progress ``` equals 0 after equals 100. Is it a bug or am I using it the wrong way?
Sorry for my English.

**Comment by TheAssassin** [comment]
A few comments on your code:

```cpp
std::this_thread::sleep_for(std::chrono::milliseconds((int)(1000.0f / 1.0f))); //small sleep time.
```

Let's break up that statement, as there's a lot of redundancy. `1000.0f/1.0f` (should) return `1000.0f` (in a perfect world, it's floating point so there might be imprecision). therefore the division here is quite pointless. You're casting the floats to int afterwards, so why not just write `1000` and avoid any sort of floating point unit?
Another issue is you write "small sleep time". In fact, 1000 ms = 1s. So it's not as small as you might expect.
What you're doing here is basically "sampling" the progress in 1s steps. That's not really fine grained, you will miss lots of status updates that way. If you want to "validate" that the progress is updating, you'd have to do this much more fine grainedly (e.g., every 1 ms).
Hence, this is a very imprecise attempt to quantize the progress updates (assuming they're modeled as a continous graph). That probably explains why progress goes from 0 to 100 without any intermediate steps: you miss all the intermediate updates.

I can't see what AppImage you're trying to update. If your network/Internet connection is quick enough, and your AppImage is small enough, the update might finish just fine within a second, it's a realistic scenario.

I noticed that you're returning `0` in case of errors. In just one case, you write a message additionally, but for instance in the block `if (!updater.progress(progress)) {...}`, you silently exit with 0. Exit codes are the oldest and easiest way to communicate failure to the user. The value scheme is `== 0` means success, `!= 0` means failure. You should change these to `return 1;`.

**Comment by TKNgu** [comment]
Thank for help.
1. I changed sleep time to 1ms and last progress = 0 after 100.
![09 40 49](https://user-images.githubusercontent.com/33709667/47332443-80970c80-d6a9-11e8-84e8-a6b4f9399768.png)
Is ```progress``` input value alway reset to 0 if not have download update ? (I fix ```if(progress > last)``` but is unnatural).
2. One more stupid question have any software requirements or something else when push my image to AppImageHub like Google or Apple market ?

P/S AppImage is all I need to my part time game developer. If you need help I alway ready if I can @_@!
After all thanks for the help and sorry for my English.

**Comment by TheAssassin** [comment]
@TKNgu that reset to 0 looks strange to me, might be a minor workflow issue somewhere in the code. There's still a lot of legacy code below the shiny C++ interface. Please open a new issue for tracking.

AppImage hosting requires a (random) HTTP server that supports so-called range requests. Any self-hosted server will work just fine, also many hosted offerings such as GitHub etc. work (Gitlab IIRC doesn't support them yet). The two files (AppImage and `.zsync` file don't even have to be on the same server).

Feel free to pass by in the #appimage channel on Freenode. My timezone is CEST.

**Comment by TKNgu** [comment]
Thank for all.
Tôi sẽ báo cho bạn nếu tìm được gì đó mới.
P/S Sorry for my English. I use Google dich.

**Comment by probonopd** [comment]
Cảm ơn bạn đã sử dụng AppImage 👍

**Comment by TheAssassin** [comment]
Closing as resolved.
