### ISSUE TITLE
Direct links to the most update AppImageUpdate and appimageupdatetool

### ISSUE THREAD

**Issue by luzpaz** [AppImage/AppImageUpdate#105]
Is there a way to make a link to the most up to date AppImageUpdate and AppImageUpdateTool ? 

Something similiar to `https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage` ?

**Comment by probonopd** [comment]
`curl -s https://api.github.com/repos/AppImage/AppImageUpdate/releases | grep browser_download_url | grep x86_64.AppImage | grep AppImageUpdate- | grep -v zsync | cut -d'"' -f4` should do.

**Comment by probonopd** [comment]
Similarly, `curl -s https://api.github.com/repos/AppImage/AppImageUpdate/releases | grep browser_download_url | grep x86_64.AppImage | grep appimageupdatetool | grep -v zsync | cut -d'"' -f4`

**Comment by luzpaz** [comment]
@probonopd I'm creating a page over at https://www.freecadweb.org/wiki/Appimage
and I was hoping to get a direct link, it's less confusing if I don't add the above bash wizardry. Thanks, nevertheless.

**Comment by TheAssassin** [comment]
Next time, please describe your use case a bit more detailedly. You're not the first one requesting static filenames for this tool.

**Comment by luzpaz** [comment]
I will. I try but sometimes, I can't think of the correct jargon.

**Comment by probonopd** [comment]
Giving some background ("I would like ... to do ... because ...) usually helps :+1:

**Comment by TheAssassin** [comment]
Closing as duplicate of #89.
