### ISSUE TITLE
Get rid of the dependency on the curl command line tool

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#11]
This functionality could be handled by zsync_curl as well

**Comment by TheAssassin** [comment]
What exactly is curl used for?

**Comment by probonopd** [comment]
Accessing the GitHub API to figure out the download URL to the "latest" release, for example.
https://github.com/AppImage/AppImageUpdate/blob/master/AppImageUpdate.AppDir/usr/bin/appimageupdate#L169

**Comment by TheAssassin** [comment]
I wouldn't invest too much into this, as we plan to replace AppImageUpdate with a proper application soon.

**Comment by probonopd** [comment]
Agree...

**Comment by TheAssassin** [comment]
Rewrite does now depend on libcurl rather than the curl CLI application. Closing.
