### ISSUE TITLE
Build libappimageupdate-qt.a

### ISSUE THREAD

**Issue by technic** [AppImage/AppImageUpdate#110]
Hi,
There is static libappimageupdate, but no  libappimageupdate-qt. Could we have it also static, so I can link it easily from qmake.

**Comment by probonopd** [comment]
Hi @technic welcome to AppImage. You may also be interested in https://github.com/antony-jr/AppImageUpdaterBridgePlugin, a Qt plugin that one of our users has been working on. That does not even require compilation. But it is very experimental right now; nevertheless I'd be interested in what you think about that approach as well. Thanks.

**Comment by TheAssassin** [comment]
@technic shouldn't be quite difficult to set up.

**Comment by technic** [comment]
> @technic shouldn't be quite difficult to set up.
Do you mean that I should setup my build with *.so?

**Comment by TheAssassin** [comment]
Now, CMake builds a static library that you can link to.

**Comment by technic** [comment]
Great!
