### ISSUE TITLE
Update information missing error message

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#113]
Under which circumstances does this nag screen appear?

There is a typo,

> upupdateinformation

![](https://user-images.githubusercontent.com/29207169/50379779-9cbb1980-0618-11e9-8e86-9f37f6f3e7d9.png)

Source: https://github.com/antoniofaccioli/libreoffice-appimage/issues/9

**Comment by TheAssassin** [comment]
It's only shown if the update information cannot be extracted. The error message states that clearly. If update information is found but invalid (or any other error occurs), a message will be shown in the progress dialog.

PRs welcome.

**Comment by probonopd** [comment]
Most AppImages do not come with Update information. Will they all trigger this User-visible nag screen? We should nag the developers instead.

**Comment by TheAssassin** [comment]
It's an error message, ***not a nag screen***. What would you do if there's no update information?

**Comment by probonopd** [comment]
Does this appear after the user actively invoked an update? Why is this not done by AppImageUpdate? What has AppImageLauncher to do with updates?

**Comment by TheAssassin** [comment]
Err... right, that's the AppImageLauncher tool... why are you asking in the AppImageUpdate repository? I thought we were talking about the AppImageUpdate dialog.

The error message in AppImageLauncher's update utility is shown when there is no update information, just as you'd expect. If you don't believe me (whyever...), here's the source code references:

- https://github.com/TheAssassin/AppImageLauncher/blob/master/src/ui/update_main.cpp#L122
- https://github.com/AppImage/AppImageUpdate/blob/rewrite/src/qt-ui/qt-updater.cpp#L285

AppImageLauncher ships its own little utility for the simple reason that it wants to integrate updated AppImages right away. It uses AppImageUpdate's reusable Qt widget internally.

**Comment by probonopd** [comment]
> Err... right, that's the AppImageLauncher tool... why are you asking in the AppImageUpdate repository? 

This shows how confused I am - all update stuff I normally handled by AppImageUpdate. It is still unclear to me architecturally why you would want it in AppImageLauncher...

**Comment by TheAssassin** [comment]
That's not the question here. And I think it's clear why that message is shown. Closing.
