### ISSUE TITLE
Rename "rewrite" branch

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#119]
Please rename "rewrite" branch to "master", and the current "master" to "1.0"

**Comment by TheAssassin** [comment]
"1.0" doesn't make any sense to me.

**Comment by probonopd** [comment]
Yes. Obviously everything before the rewrite was the 1.x series

**Comment by RogueScholar** [comment]
Perhaps renaming the rewrite branch to "main" would be more prescient in light of GitHub's updated naming conventions? Either way, could this possibly get a priority bump? I'm about to get started packaging this up on Launchpad as a dependency for AppImageLauncher and it would be marvelous to set everything up the first time pointing at a branch name that makes long-term sense.

**Comment by probonopd** [comment]
@TheAssassin: I would say, let's do `v1` and `master` = v2

**Comment by TheAssassin** [comment]
Well, if any, I'd also go for `main`, now that we change it anyway.

I'd use `zsync-curl` for the legacy branch.

**Comment by probonopd** [comment]
maybe `legacy-zync-curl` or `v1-zync-curl` so that one sees immediately which is the old one.

**Comment by TheAssassin** [comment]
```
rewrite --> main
master --> legacy-zsync-curl
```

**Comment by probonopd** [comment]
Thank you @TheAssassin
