### ISSUE TITLE
Do not use symlinks for desktop files

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#120]
https://github.com/AppImage/AppImageUpdate/blob/00053b7f8f8ff1e0693dff3015cb4ae5a42cfac8/resources/build-appimages.sh#L90

This seemingly creates a symlink for the top-level desktop file. Please create a copy instead.
I was unable to locate the code where the symlink gets created.

Reference:
https://github.com/AppImage/appimaged/issues/54

**Comment by TheAssassin** [comment]
Symlinks should be/are handled by libappimage. No need for fixes IMO, especially not in this repo. If you want to suggest changes for linuxdeploy, please create issues there.
