### ISSUE TITLE
Make it look native on Gtk systems

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#124]
Please make it look native on Gtk systems using

```
apt-get update
apt-get -y install libgtk2.0-dev
git clone http://code.qt.io/qt/qtstyleplugins.git
cd qtstyleplugins
qmake
make -j$(nproc)
sudo make install 
cd -
```

and deploying `platformthemes/libqgtk2.so` and `styles/libqgtk2style.so`.

**Comment by TheAssassin** [comment]
PRs welcome.

**Comment by probonopd** [comment]
Where would I put this code? (It's not easy for me to find out where this should go.)

**Comment by probonopd** [comment]
`AppImageUpdate/resources/bootstrap-container.sh`?

**Comment by TheAssassin** [comment]
Yep, that's the place. I have it open, too, so if you didn't start yet, I can just put it in, too.

**Comment by probonopd** [comment]
Please go ahead.

**Comment by TheAssassin** [comment]
I've started to implement support for the platform themes and styles, too. I'm just copying the `platformthemes`/`styles` directories from the plugins directory. I suppose that's the right way, isn't it?

**Comment by TheAssassin** [comment]
Copying all styles might be a bit overkill, including the Gtk 2 stuff it's ~ 15 MiB (uncompressed).

**Comment by TheAssassin** [comment]
@probonopd please check https://github.com/linuxdeploy/linuxdeploy-plugin-qt/commit/cbc0b47904cf3487a4c38ed5876589382a4cd940.

**Comment by probonopd** [comment]
I think that we should deploy the platform themes and styles but _not_ their dependencies. If the dependencies are not there, then the plugin should not be used anyway since their whole point is that they only run to match what is on the system; and I think Qt plugins will just silently fail if dependencies are unmet.

Does this make sense?

**Comment by TheAssassin** [comment]
Pretty sure excluding the dependencies is not such a great idea. I have to fix the AppImageUpdate build, then we can check whether it works as intended. If not, we'll try just copying the files without the dependencies.

**Comment by probonopd** [comment]
Please have a look again at this @TheAssassin as you have just implemented this successfully for AILL

**Comment by TheAssassin** [comment]
Well, the theme there is *completely broken*. I wouldn't call this a success...

**Comment by probonopd** [comment]
What is broken about it? Works well for me.

**Comment by TheAssassin** [comment]
All the missing icons, weird button sizes, ...?

**Comment by probonopd** [comment]
The icons are imho minor (can probably be fixed by bundling the icons or not using icons on the buttons) and the button sizes look correct (like on Xfce) to me, what do you think is wrong about the button sizes?

**Comment by probonopd** [comment]
Introduces more hassle than it is worth.
