### ISSUE TITLE
How to troubleshoot failed update

### ISSUE THREAD

**Issue by DamirPorobic** [AppImage/AppImageUpdate#125]
It looks like I'm not able to update my Application via AppImageUpdate but it used to work. Now I get following when I try to update it:
```
$ ./AppImageUpdate-x86_64.AppImage ./ksnip-1.6.0-continuous.AppImage
AppImageUpdate version 1-alpha (commit 6f2d028), build 400 built on 2019-02-07 22:44:08 UTC
Fetching release information for tag "continuous" from GitHub API.
None of the artifacts matched the pattern in the update information. The pattern is most likely invalid, e.g., due to changes in the filenames of the AppImages. Please contact the author of the AppImage and ask them to revise the update information.
ZSync URL not available. See previous messages for details.
```
How can I troubleshoot such an issue? The zsync file is there on the release page: https://github.com/DamirPorobic/ksnip/releases/tag/continuous

**Comment by TheAssassin** [comment]
Get appimageupdatetool and run it with `-d` on the AppImage. It should display the update information. Please post the output here. It's probably wrong.

**Comment by probonopd** [comment]
https://github.com/DamirPorobic/ksnip/releases/download/continuous/ksnip-1.6.0-continuous.AppImage has gh-releases-zsync|DamirPorobic|ksnip|continuous|ksnip*-x86_64.AppImage.zsync as a quick `wget "https://github.com/DamirPorobic/ksnip/releases/download/continuous/ksnip-1.6.0-continuous.AppImage" -O - | strings | grep zsync` shows.

**Comment by DamirPorobic** [comment]
I see, yeah that was a recent change. And there is no way to drop that suffix, it must be present? 
Anyways, thanks for the investigation.

**Comment by TheAssassin** [comment]
Well, you can drop it, sure, but you shouldn't. It's very important for users to see what platforms an AppImage will be running on. There's a growing community of ARM users (especially through chromebooks and that stuff), and there's a lot of people who still use i386 for some reason...

**Comment by DamirPorobic** [comment]
Ok, thanks for the help and feedback.
