### ISSUE TITLE
Missing AppImage packages in "continuous" release

### ISSUE THREAD

**Issue by aferrero2707** [AppImage/AppImageUpdate#127]
The [continuous release](https://github.com/AppImage/AppImageUpdate/releases/tag/continuous) does not contain the AppImage packages for `AppImageUpdate` and `appimageupdatetool`, while several help pages (like [this one](https://github.com/AppImage/AppImageUpdate/wiki/Example:-Step-by-step-walkthrough-with-%60appimageupdatetool%60)) suggest to download the packages from there.

Is this just a temporary issue, or are those AppImage packages deprecated?

Thanks for all your work!

**Comment by TheAssassin** [comment]
I had triggered a rebuild, and to allow it to upload the binaries, I have to delete the old ones (uploadtool doesn't overwrite for some reason, CC @probonopd).

Will retrigger and then monitor the build. Thanks for the hint!

**Comment by aferrero2707** [comment]
FYI, I have a script to delete release assets matching a given prefix and suffix: https://github.com/aferrero2707/uploadtool/blob/master/remove.sh

Maybe you'll find it useful...

**Comment by probonopd** [comment]
@TheAssassin what happened here? If a build fails, then the upload script should normally not run at all. How come that not even the last version that still worked is available for download anymore?

**Comment by TheAssassin** [comment]
@aferrero2707 fixed. Problem was that I hadn't rebuilt the curl packages on openSUSE build service in 2 years (they just worked fine...), and the key had expired. Took me a bit to figure that out. I expected OBS to keep things running, to be honest. I rebuilt the PPA there, and now the build works just fine again.

**Comment by devnoname120** [comment]
Might want to unpin this issue now that it's fixed.
