### ISSUE TITLE
Investigate xdelta3

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#13]
https://github.com/jmacd/xdelta

What are its pros/cons vs. zsync?

**Comment by TheAssassin** [comment]
@probonopd we haven't looked into this any further for a few months. Is it still of any relevance?

**Comment by probonopd** [comment]
As I have not yet looked into it, I don't know what are its pros/cons vs. zsync would possibly be, but since we are now going with zsync and it is working well for us there is no immediate need to investigate this. Hence closing for now. Anyone is free to reopen this issue if they think we should look into it.
