### ISSUE TITLE
self-update not working on apps executed with AppImageLauncher

### ISSUE THREAD

**Issue by azubieta** [AppImage/AppImageUpdate#131]
If an application uses `libappimageupdate` to do self-updates. The AppImage file path is resolved using the APPIMAGE environment variable. But when the application is executed using AIL it's exposed in the AIL_FS and the path returned by the APPIMAGE environment variable is not the real one which makes the process to fail.

**Comment by TheAssassin** [comment]
I guess the quickest workaround is to have AppImageLauncher export an environment variable by itself. But that will then only work in the latest versions of AppImageLauncher. Another option would be to offer some sort of `ail_realpath` (similar to the real `realpath`) for use inside libappimageupdate to look up the original path.
