### ISSUE TITLE
--check-for-update either should output the pending upstream version is or a new flag should be created  

### ISSUE THREAD

**Issue by luzpaz** [AppImage/AppImageUpdate#137]
So:
```
      -j, --check-for-update            Check for update. Exits with code 1 if
                                        changes are available, 0 if there are
                                        not,other non-zero code in case of
                                        errors.
```

When run it outputs this:  

```
$ ./appimageupdatetool-x86_64.AppImage -j FreeCAD_0.19-18522-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage 
Fetching release information for tag "0.19_pre" from GitHub API.
$
```

Is it possible to just go ahead a throw in the pending version update info in there while we're at it? 

FYI, I do recognize that the `-d` flag returns that info 

```
$ ./appimageupdatetool-x86_64.AppImage -d FreeCAD_0.19-18522-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage 
Fetching release information for tag "0.19_pre" from GitHub API.

Parsing file: FreeCAD_0.19-18522-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage
AppImage type: 2
Raw update information: gh-releases-zsync|FreeCAD|FreeCAD|0.19_pre|FreeCAD*glibc2.12-x86_64.AppImage.zsync
Update information type: ZSync via GitHub Releases
Assembled ZSync URL: https://github.com/FreeCAD/FreeCAD/releases/download/0.19_pre/FreeCAD_0.19-18589-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage.zsync
```

So It's very verbose which I don't mind except that it's hard to immediately pick out that an update is available and what version/revision number said update is. So perhaps cleaning up the output of the -d flag or making a new flag that simply outputs the pending upstream file in a succinct way ?

**Comment by TheAssassin** [comment]
There's no "upstream version" we could output. We just check compare the local file against the `.zsync` file to see whether there are changes. AppImageUpdate doesn't know about any version numbers, it doesn't need them and cannot provide them to you therefore.

If you look at the "raw update information", that `0.19_pre` tag is hardcoded in there. That seems wrong, actually, as that'll prevent updates to newer versions. If you check https://github.com/AppImage/AppImageSpec/blob/master/draft.md#github-releases, you'll see that one should actually use `latest`, a magic string that'll point to the latest regular release.

**Comment by luzpaz** [comment]
if that's the case then we'd use `continuous` since it's a pre-release. But that's not useful in this case since we want to visually see what revision the AppImage is in comparison to the other development builds (see the listed [Assets](https://github.com/FreeCAD/FreeCAD/releases/tag/0.19_pre) for 0.19_pre). 

Thanks anyway. I'll close this ticket now

**Comment by TheAssassin** [comment]
Perhaps @probonopd has an idea that might help you get the information you need?

AppImageUpdate is built around the idea that it's sufficient to know whether there's an update, not what exact version you're updating to.

**Comment by probonopd** [comment]
> Perhaps @probonopd has an idea that might help you get the information you need?

Probably it's doable using the [GitHub API](https://developer.github.com/v3/) but possibly doing so is outside of the scope of AppImageUpdate.
