### ISSUE TITLE
zsync2: Reading and/or parsing .zsync file failed!

### ISSUE THREAD

**Issue by conradjones** [AppImage/AppImageUpdate#143]
Getting this error, when updating from in my app. `zsync2: Reading and/or parsing .zsync file failed!`

This happens on fedora, it works on ubuntu. I build AppImageUpdate and that got the same error when I build AppImageUpdate from the command line. with `cmake .. -DCMAKE_BUILD_TYPE=Debug`

i loaded appimageupdate into CLion and it works when i build it from there, this is not making much sense to me, as I was hoping to step into it in clion to debug it.

**Comment by conradjones** [comment]
Ok, i think AppImageUpdate tool must have been checking itself not my app when I ran it from CLion the first time.  the issue is the root CA for the cert on my server is not trusted in fedora. 

So not really an issue, but some better feedback would have been helpful in this case.

**Comment by conradjones** [comment]
this would help
`diff --git a/src/zsclient.cpp b/src/zsclient.cpp
index 83eaaf8..1f2c7ef 100644
--- a/src/zsclient.cpp
+++ b/src/zsclient.cpp
@@ -312,8 +312,10 @@ namespace zsync2 {
                     auto response = session.Get();
 
                     bool digestVerified;
-                    if (!verifyInstanceDigest(verificationResponse, response, digestVerified))
+                    if (!verifyInstanceDigest(verificationResponse, response, digestVerified)) {
+                        issueStatusMessage(verificationResponse.error.message);
                         return nullptr;
+                    }
 
                     // expecting a 200 response
                     if (!checkResponseForError(response, 200))`

**Comment by TheAssassin** [comment]
Please feel free to send a PR over at zsync2's repository, then we can update the dependency here and incorporate your change.

**Comment by antony-jr** [comment]
@TheAssassin Please close this issue as it is resolved. I think this repo might need the **stale bot**.
