### ISSUE TITLE
Signature verification for self-updating appimages ?

### ISSUE THREAD

**Issue by JocelynDelalande** [AppImage/AppImageUpdate#146]
I saw discussion about signature verification using AppImageUpdate : https://github.com/AppImage/AppImageUpdate/issues/16 ; the interesting aspect  is the [TOFU](https://en.wikipedia.org/wiki/Trust_on_first_use) mechanism (validate that the signature remains the same accross updates).

How about self-updating images, do they use this validation mechanism ?

The [doc](https://docs.appimage.org/packaging-guide/optional/updates.html) says it is a work-in-progress, but the linked issue is about AppImageUpdater.

Thanks by advance.

**Comment by JocelynDelalande** [comment]
Thanks, I think I better understand something : I though AppImageUpdate was an external application, I just understood that it was meant to be bundled with the packaged app.

And you seem to tell that there are several ways to handle updates, but that they all support the kind of verification that I am looking for. Thanks a lot @TheAssassin :-).

**Comment by TheAssassin** [comment]
You're welcome. Please feel free to send a PR to our [docs repo](https://github.com/AppImage/docs.appimage.org) to update the update section if you think there is room for some clarification.

**Comment by TheAssassin** [comment]
Closing as resolved.
