### ISSUE TITLE
AppImageUpdate look and feel in gtk desktops

### ISSUE THREAD

**Issue by ghost** [AppImage/AppImageUpdate#147]
Make a gtk AppImage Updater.

**Comment by probonopd** [comment]
It may be sufficient to bundle 

```
plugins/styles/libqgtk2style.so
plugins/platformthemes/libqgtk2.so
```

to get a GTK-native look.

Reference:
https://github.com/AppImage/AppImageKit/wiki/Bundling-Qt-apps#theming-on-gtk-systems

**Comment by probonopd** [comment]
If you want a Gnome look and feel, then maybe the actively developed
https://github.com/FedoraQt/QGnomePlatform
