### ISSUE TITLE
Link in README to continuous AppImage build of Subsurface 404s

### ISSUE THREAD

**Issue by sitic** [AppImage/AppImageUpdate#148]
The link in the [Try it out](https://github.com/AppImage/AppImageUpdate#try-it-out) section of the README to a [continuous AppImage build of Subsurface](https://github.com/Subsurface-divelog/subsurface/releases/tag/continuous) 404s. They don't seem to have a `continuous` anymore.

**Comment by probonopd** [comment]
The switched to GitHub Actions, maybe that has to do with it. Anyhow, thanks for letting us know.

@TheAssassin could you please switch the link to https://github.com/subsurface/subsurface/releases?

**Comment by TheAssassin** [comment]
You can do it yourself, I guess?

**Comment by probonopd** [comment]
No, I always edit the wrong files... because I never know where to edit ;)

**Comment by TheAssassin** [comment]
It's literally just the README of this repository. I don't think you can break this at all, there's no external strings attached to it?

**Comment by probonopd** [comment]
Aaah, I misread. Thanks!
