### ISSUE TITLE
execv() failed: No such file or directory

### ISSUE THREAD

**Issue by justdanyul** [AppImage/AppImageUpdate#156]
I tried downloading AppImageUpdate-i386.AppImage, made it executable, and tried running it from the command line, which results in `execv() failed: No such file or directory` 

It doesn't matter if i run it with out parameters, or if i try giving it another app image as parameter name, i get the same result. What am I doing wrong?

(just to be clear, I'm using i3 so I dont have the desktop actions available to try out, so I'm hoping to update from the terminal)

**Comment by TheAssassin** [comment]
Please provide at least the utter minimum of information. What distro/version?

**Comment by probonopd** [comment]
Are you on a i386 distribution at all?
