### ISSUE TITLE
Missing build for appimageupdatetool

### ISSUE THREAD

**Issue by shoogle** [AppImage/AppImageUpdate#162]
The latest continuous release has no binary for appimageupdatetool. This has broken build scripts for MuseScore in an unexpected way, causing nightly AppImages to shoot up in size.

![MuseScore_nightlies_massive](https://user-images.githubusercontent.com/11011881/101922103-a0f5ee00-3bc5-11eb-831b-be66ea8a50a9.png)

Also, would be great to have numbered version releases of AppImageUpdate rather than always continuous. This way our build scripts can always use the last-known-good version to avoid temporary breakages like this. New versions don't have to be released very often.

**Comment by TheAssassin** [comment]
Very surprising result, the filesize goes *up*, not down...

Should be fixed within the next minutes. I forgot to upload the appimageupdatetool AppImages as artifacts in the workflow file.
