### ISSUE TITLE
[rewrite] Segfault when appimageupdategui-x86_64.AppImage tries to update itself

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#17]
```
me@host:~$ wget https://transfer.sh/Kljvv/appimageupdategui-x86_64.AppImage
me@host:~$ chmod a+x appimageupdategui-x86_64.AppImage
me@host:~$ /appimageupdategui-x86_64.AppImage appimageupdategui-x86_64.AppImage 
Checking for updates...
Speicherzugriffsfehler
```

**Comment by TheAssassin** [comment]
You should know where the bug comes from. It's because of the broken cURL that is bundled at the moment. Hence closing as duplicate of https://github.com/TheAssassin/zsync2/issues/4.

**Comment by TheAssassin** [comment]
That said, you can try to un-bundle libcurl, libssl etc. from the AppImage you download as a workaround.

**Comment by TheAssassin** [comment]
Confirming that this works, just delete `usr/lib/libcurl-gnutls.so.4` and the application will work as intended.
