### ISSUE TITLE
AppImageUpdate and sources from the repository of a distro

### ISSUE THREAD

**Issue by ivan-hc** [AppImage/AppImageUpdate#177]
Scenario:
I can built AppImages for Chromium (from Slackware repository), qBittorrent (ppa), Opera, Vivaldi, Edge, Spotify (from their official .deb packages) and other programs (also from tar.zst files of Arch/AUR).

Have I to create the AppImage on a repository or is it possible to integrate instructions to detect when a new release is available from each original source (and then running a script to rebuilt them)?

If yes, I can finally solve a part of this other [issue](https://github.com/ivan-hc/AppMan/issues/2).

Thanks in advance.

**Comment by probonopd** [comment]
AppImageUpdate is a tool for the end user to update AppImages. It has nothing to do with how these AppImages get build, which I understand your question is about. So closing here.
