### ISSUE TITLE
Increase verbosity in error messages

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#18]
As the user, I would like to know
* Did the AppImage provide no update information this version of AppImageUpdate can understand? In this case, I may want to update to the latest AppImageUpdate
* Was there no Internet connectivity? In this case, I may want to switch on WLAN
* Was there an issue with the HTTPS certificates? In this case, I may want to check my clock
etc.

![deepinbildschirmfoto20171029100007](https://user-images.githubusercontent.com/2480569/32142068-13295f4c-bc90-11e7-9cbf-a43ac258e6d3.png)

**Comment by TheAssassin** [comment]
Please add the [rewrite](https://github.com/AppImage/AppImageUpdate/milestone/1) milestone rather than tagging the title with `[rewrite]`, thanks.

**Comment by TheAssassin** [comment]
I've improved this by making sure to fetch the status messages once after the update check has been performed, which shows all the messages the update check produces in the main window. That should be enough for debugging purposes. The last most message is logically the error message.

I've further improved the error messages this dialog can show.

Lastly, AppImageUpdate now asks to check for an update of itself in case any update check error occurs. This should further be done in case the regular update process fails.

A few "unknown error" cases are most likely left however, I'd say we should implement messaging one by one when they're reported.

Please check again, I think we can close this issue.
