### ISSUE TITLE
Where does the new appimage url come from?

### ISSUE THREAD

**Issue by SevenBlocks** [AppImage/AppImageUpdate#183]
I'm trying to figure out how to create an AppImage that can be easily updated by the client, but I don't understand what URL the updated AppImage should be published to.

I've used `linuxdeployqt -updateinformation="zsync|https://myserver/Application-latest-x86_64.AppImage.zsync"`
so that my appimage has the url to the .zsync file, which I can host on my server.

I can bundle AppImageUpdate tool in my appimage, but where do I publish the new AppImages to? Should it be at the url `https://myserver/Application-latest-x86_64.AppImage` (without the .zsync)? This isn't documented anywhere that I can find.

**Comment by probonopd** [comment]
Please see https://github.com/AppImage/AppImageSpec/blob/master/draft.md#zsync-1.
