### ISSUE TITLE
Possibility to do whole update trough provided CLI tool only?

### ISSUE THREAD

**Issue by p-bo** [AppImage/AppImageUpdate#189]
From help for appimageupdatetool :

> AppImage companion tool taking care of updates for the command line.

But it seems, that this tool itself isn't able to actually perform any update (only provides information necessary to supply to another tool).

It would be helpful to be able to do update process from CLI - for scripting, integration into other tools - for example https://github.com/r-darwish/topgrade/issues/814

**Comment by TheAssassin** [comment]
Of course it can. `./appimageupdatetool*.AppImage <someother.AppImage>`.

**Comment by JonLit** [comment]
> Of course it can. `./appimageupdatetool*.AppImage <someother.AppImage>`.

Is it also possible to do this from a terminal without the GUI opening? At the moment I always have to click close after the update
