### ISSUE TITLE
Unable to update appimages using gh-releases-zsync

### ISSUE THREAD

**Issue by ProjectSynchro** [AppImage/AppImageUpdate#193]
Hi, I'm currently testing AppImage updates for nightly builds of [Naev](https://github.com/naev/naev)

I am running into the following error when attempting to update using `appimageupdatetool`(Release 2.0.0-alpha-1-20220117):
[naevTestUpdate.txt](https://github.com/AppImage/AppImageUpdate/files/7896041/naevTestUpdate.txt)

The following line messages seem to be of interest:
```
zsync2: Verifying downloaded file
100.00% done (401.90 of 401.90 MiB)...
zsync2: checksum matches OK
zsync2: used 415182848 local, fetched 6800576
100.00% done (401.90 of 401.90 MiB)...
Failed to create temporary directory: Invalid argument
Validation error: Failed to create temporary directory
Restoring original file
```
The above AppImage was built using linuxdeploy (via the appimage plugin), with the following: `gh-releases-zsync|naev|naev|nightly|naev-*.AppImage.zsync` embedded as the update URL. This link appears correct otherwise AppImageUpdate would have told me otherwise, and wouldn't have been able to get to the point it fails at.

Just to rule out there being some sort of issue with my linux distro (Fedora 35), I booted up an Ubuntu 20.04 VM and saw the same behaviour. 

Out of curiosity I also tested an older version of AppImageUpdate [From this CI run](https://github.com/AppImage/AppImageUpdate/actions/runs/1708537463) observing the same behaviour:
[AppImageUpdateTestUpdate.txt](https://github.com/AppImage/AppImageUpdate/files/7896097/AppImageUpdateTestUpdate.txt)

Interesting lines:
```
zsync2: Verifying downloaded file
100.00% done (28.73 of 28.73 MiB)...
zsync2: checksum matches OK
zsync2: used 25856000 local, fetched 4846784
100.00% done (28.73 of 28.73 MiB)...
Failed to create temporary directory: Invalid argument
Validation error: Failed to create temporary directory
Restoring original file

```
Is this an issue with zsync2 or with AppImageUpdate?
How can I further debug what is going awry? The error message is cryptic but points to an incorrect argument being passed to something.

Cheers.

**Comment by Marshallishere** [comment]
I'm having this same problem on Solus, can't even update appimageupdatetool.

**Comment by Kirtai** [comment]
Exact same problem on Debian sid.

**Comment by munix9** [comment]
The same problem on openSUSE Tumbleweed.

**Comment by ProjectSynchro** [comment]
Looks like this isn't distro specific issue based on others in the thread. Changed the title to reflect that.

**Comment by TheAssassin** [comment]
I've changed a couple of things recently. I use Ubuntu 20.04 myself on multiple computers and have not seen such issues at all. I'll have a look ASAP.

**Comment by TheAssassin** [comment]
Folks, I need links to such AppImages. The issue you see is related to signature validation, so I need hands on signed AppImages.

**Comment by Marshallishere** [comment]
I can't update appimageupdatetool itself and [librewolf](https://gitlab.com/api/v4/projects/24386000/packages/generic/librewolf/96.0.2-1/LibreWolf.x86_64.AppImage).

**Comment by Marshallishere** [comment]
Also I tested an older version of [KeePassXC](https://github.com/keepassxreboot/keepassxc/releases/download/2.6.5/KeePassXC-2.6.5-x86_64.AppImage), same problem.

**Comment by TheAssassin** [comment]
Thanks. Problem identified, fix underway.
