### ISSUE TITLE
Consistent naming

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#20]
Let's use __AppImageUpdate__ as the user-facing name for the user-visible GUI application. (You will never see "GUI" in the user-facing name of commercial applications; grandma doesn't know what that even means.)

`appimageupdate` is the name of the command line tool, following the macOS convention that GUI applications are upper-case while command line tools are lower-case. If this distinction is not sufficient, we could also call the CLI tool `appimageupdatetool`.

**Comment by TheAssassin** [comment]
I'd make `appimageupdategui` become `AppImageUpdate`, `appimageupdate` (the CLI) would be `appimageupdateool`, and `appimageupdategui-selfupdate` would be named `AppImageSelfUpdate` (it' a GUI app, too).

Does that sound like a good idea?

**Comment by TheAssassin** [comment]
Please add the [rewrite](https://github.com/AppImage/AppImageUpdate/milestone/1) milestone rather than tagging the title with `[rewrite]`, thanks.

**Comment by TheAssassin** [comment]
Closed via 18fe42d.
