### ISSUE TITLE
Continuous build vs Release 2.x* - which one to download

### ISSUE THREAD

**Issue by slrslr** [AppImage/AppImageUpdate#200]
https://github.com/AppImage/AppImageUpdate/releases shows "Continuous build" and "Release 2.0.0-alpha..."

and it is not apparent for noob user which one to choose so one can update appimages being regular user. Searching "continuous" on a [README page](https://github.com/AppImage/AppImageUpdate#readme) does not make me understand which one i should download.
Can you make it more apparent?

**Comment by slrslr** [comment]
Without replies, I have downloaded Continuous build:

`cd $HOME/appimages/ && wget -Nc https://github.com/AppImage/AppImageUpdate/releases/download/continuous/AppImageUpdate-x86_64.AppImage && chmod +x AppImageUpdate-x86_64.AppImage && ./AppImageUpdate-x86_64.AppImage`

**Comment by probonopd** [comment]
Continuous is the latest build.
Release is the latest released build.
