### ISSUE TITLE
Prevent Gtk from being installed in the Docker container

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#202]
Prevent Gtk from being installed in the Docker container.
What is pulling it in?

**Comment by probonopd** [comment]
Docker and CMake... cost me way too much time today. And I still don't know why Gtk is ending up in the Docker container.

**Comment by TheAssassin** [comment]
What Docker container do you mean? You're not providing nearly enough information...

**Comment by TheAssassin** [comment]
Could you please stop experimenting on `main`?

![screenshot_2022-05-21_20-46-03](https://user-images.githubusercontent.com/4503202/169665241-c3f997c8-b2ed-46a3-96db-c00791f53e17.png)

**Comment by probonopd** [comment]
> What Docker container do you mean? You're not providing nearly enough information...

The Docker container that builds the AppImageUpdate AppImages.

> Could you please stop experimenting on main? This is really bad style.

Thing is, with each commit I thought "this is it". Didn't imagine it to be so hard. Will work on a branch next time.

**Comment by TheAssassin** [comment]
As mentioned in https://github.com/AppImage/AppImageUpdate/issues/150#issuecomment-1133753152, this is simply the wrong question to ask. All these commits are really, really, really bad hacks. The Gtk+ stuff is pulled in as dependencies of the packages.

Closing here therefore in favor of #150. I'll push a single-commit revert for all these previous commits, and will fix the issue in linuxdeploy-plugin-qt.
