### ISSUE TITLE
Option to ignore appimages in specified directories?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [AppImage/AppImageUpdate#208]
Some Linux distributions, have facilities for installing AppImages to system directories, e.g. some Arch Linux AUR scripts install AppImages to somewhere in `/opt`, and set up desktop files and such for them. The problem is, any time I launch such an application, AppImageUpdate will ask if I want to integrate it. It would be nice if I could tell AppImageUpdate to ignore AppImages in certain directories (i.e. it should assume they are already integrated).

**Comment by TheAssassin** [comment]
This is not AppImageLauncher's issue tracker. You want to file your issue there. https://github.com/TheAssassin/AppImageLauncher
