### ISSUE TITLE
Follow common GUI guidelines

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#22]
In line with other GUI applications (example: Firefox), let's have 

* The default (OK) button in the bottom right
* The cancel button to the left of the default button
* No icons inside the buttons
* No punctuation (!, .) inside buttons
* No exclamation marks in text in dialog boxes

This will make the UI look more familiar and in line with most applications.

Screenshot: How Firefox asks when opening files marked as executable (e.g., by `appimaged`). Note: This is a Firefox dialog, not something from AppImageKit.

![screenshot from 2017-10-30 16-26-46](https://user-images.githubusercontent.com/2480569/32179267-469dba6c-bd8f-11e7-9d7d-56c1fa9043a7.png)

Screenshot: AppImageUpdate

![screenshot from 2017-10-30 16-30-34](https://user-images.githubusercontent.com/2480569/32179443-b27c6d28-bd8f-11e7-8991-97ef52fcac8d.png)

**Comment by TheAssassin** [comment]
Well, I don't agree that they're necessarily *common* guidelines. But let's have a look:

> The default (OK) button in the bottom right

That won't work very well with FLTK, as the left button is the one selected by default as you can see in the screenshot. I'd rather leave it that way, than having the Exit button be highlighted by default.

> No icons inside the buttons

I don't know whether that's possible with FLTK by default.

> No punctuation (!, .) inside buttons

That change's fairly easy.

> No exclamation marks in text in dialog boxes

I've seen them elsewhere, and don't think it's a big deal. However, I don't mind changing.

PRs welcome!

**Comment by TheAssassin** [comment]
I think the current UI is okay as it is, since this issue hasn't been updated ever since October.
