### ISSUE TITLE
Only show progress bar if there is progress to show

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#23]
In this case, there is no download progress to show, hence we should _only_ show the topmost window:

![screenshot from 2017-10-30 16-23-14](https://user-images.githubusercontent.com/2480569/32180726-0d340ca0-bd93-11e7-97a9-d103fec2d277.png)

In other words, only show the progress bar window if the progress is > 0%.

**Comment by TheAssassin** [comment]
Lowering priority as a new Qt based UI is in discussion.

**Comment by antony-jr** [comment]
@TheAssassin , Any Feedbacks on  [this](https://github.com/antony-jr/AppImageUpdater). Reviews are much appreciated. ( Just letting you know that the project is finished almost! ).
![AppImage Updater](https://raw.githubusercontent.com/antony-jr/AppImageUpdater/master/.img/poster.png)

**Comment by TheAssassin** [comment]
Please don't advertise competing projects... (why is that even something worth mentioning?)

**Comment by TheAssassin** [comment]
The new Qt UI prototype works fine design wise. Closing.
