### ISSUE TITLE
Handle special characters in path to AppImage

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#26]
Need to gandle special characters (such as brackets and whitespace) in the path to the AppImage when supplied on the command line:

![deepinbildschirmfoto20171030223339](https://user-images.githubusercontent.com/2480569/32196890-7cfcb814-bdc2-11e7-8f24-e3ef7a53e782.png)

**Comment by probonopd** [comment]
Hold on, likely my mistake...

**Comment by TheAssassin** [comment]
You passed the string `Downloads/AppImageUpdate-x86_64` (without the rest of the original path) to AppImageUpdate, which correctly stated it doesn't exist and showed an error.

**Comment by probonopd** [comment]
Indeed.

**Comment by TheAssassin** [comment]
![fastest-ever-issue-rejection](https://user-images.githubusercontent.com/4503202/32197052-1ec5474c-bdc3-11e7-86e1-ad6a67d15772.jpg)
