### ISSUE TITLE
--version

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#27]
It would be cool if we could somehow find out the version of the locally downloaded AppImageUpdate and `appimageupdatetool`.

**Comment by TheAssassin** [comment]
How should we realize that? How do linuxdeployqt and AppImageKit solve the issue?

The only version identifier currently available is the Git commit ID, I guess.

**Comment by probonopd** [comment]
Which would be great.

https://github.com/AppImage/AppImageKit/blob/3329f42f0c5d13b754e1a73f877725846682ded7/shared.c#L456-L459

**Comment by TheAssassin** [comment]
I implemented a beta for this, the binaries now show their current version on every call. Please check if it suits your needs. Will eventually be replaced by a `--version` argument, as soon as a real argument parser has been implemented.

**Comment by probonopd** [comment]
Works for me in `appimagetool`:

```
me@host:~$ ./Downloads/appimageupdatetool-x86_64.AppImage foo
AppImageUpdate version 1-alpha (commit f640410), build 106 built on 2017-11-02 16:09:00 UTC
```

It would be nice if it would show this when invoked without parameters, too (until there is parameter parsing). Same for AppImageUpdate, where I did not see the message.

**Comment by TheAssassin** [comment]
Great idea, I'll move the code up a bit.

**Comment by TheAssassin** [comment]
Version messages are displayed. Also, the filenames contain version information, now, too.
