### ISSUE TITLE
Self-updating AppImages

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageUpdate#30]
Continuation of the discussion in https://github.com/AppImage/AppImageKit/issues/133.

It would be nice to offer some tools allowing AppImages to check for updates and eventually update themselves, which can be used in special cases where this feature is required.

Therefore, a binary called `AppImageSelfUpdate` (a modified variant of the new GUI `AppImageUpdate`) has been implemented, making self-updates as easy as calling a subprocess.

The idea is that `AppImageSelfUpdate` can configure itself from the environment so that the binary just needs to close itself and call that binary using an `exec()` call.

A feature that is missing at the moment is to offer AppImages an "update check" using the algorithms implemented in `AppImageSelfUpdate` anyway.

We are working on such a concept at the moment in a wiki page here: 
https://github.com/AppImage/AppImageUpdate/wiki/Self-updating-AppImages. This page is going to be updated with a more final concept soon.

**Comment by probonopd** [comment]
> Therefore, a binary called AppImageSelfUpdate (a modified variant of the new GUI AppImageUpdate) has been implemented, making self-updates as easy as calling a subprocess.

What I still can't wrap my head around is why we need a separate binary for this rather than just using the regular libappimageupdate or AppImageUpdate, depending on how deeply the application author wants to integrate the update functionality into the app's look and feel.

**Comment by TheAssassin** [comment]
> What I still can't wrap my head around is why we need a separate binary for this rather than just using the regular libappimageupdate or AppImageUpdate, depending on how deeply the application author wants to integrate the update functionality into the app's look and feel.

The idea is to provide this functionality to _any_ application whatever language they use. An Electron or Python based app can't "just use" libappimageupdate. Also, libappimageupdate doesn't provide self-updating, it's `AppImageSelfUpdate` which implements this with just a few library calls (not to mention it's really easy to call a subprocess via `exec()` (any language has an equivalent of this), but adding a dependency on another library usually is quite problematic). AppImageSelfUpdate provides a UI for this already that looks exactly the same as the main UI, so that saves quite some work as well.

Nobody stops you from using libappimageupdate directly, but the easiest way of providing this functionality is just to have a separate binary that is bundled in the AppImage.

**Comment by probonopd** [comment]
Couldn't we have AppImageUpdate do that as well (dual use: standalone vs. embedded inside another AppImage)?

**Comment by TheAssassin** [comment]
No, because AppImageUpdate should update other AppImages as well when being packaged as an AppImage itself. AppImageSelfUpdate won't be packaged as an AppImage therefore.

**Comment by probonopd** [comment]
Why not put AppImageUpdate.AppImage into the AppImage that is supposed to be (auto) self updating?

**Comment by TheAssassin** [comment]
Because then you'd obviously have set the relevant environment variables to AppImageUpdate's AppImage. Also in this relation being automagic and detecting whether AppImageUpdate is packaged into another AppImage or not could lead to a lot of confusion. As I'm using the same file to generate both applications, it is also not much of a hassle to maintain both.

**Comment by probonopd** [comment]
I'm not sure I understand. Whenever the payload application thinks it would be a good idea to check for updates, then it could exec AppImageUpdate?

**Comment by TheAssassin** [comment]
That's the idea. You call `AppImageSelfUpdate --update-check` (not the final API, just so you get the idea) to see whether an update is available, the exit code contains that information. Eventually, you just `exec(...)` AppImageSelfUpdate (to close the current application, too), and AppImageSelfUpdate will update and re-open the current AppImage.

**Comment by TheAssassin** [comment]
This is a lot easier to integrate than building and linking to libappimageupdate, as it just needs a few calls to the standard library of the current programming language.

**Comment by probonopd** [comment]
This is what Subsurface currently does (independently of AppImage):

![screenshot_2017-11-04_13-04-46](https://user-images.githubusercontent.com/2480569/32405197-de0e0e86-c160-11e7-922a-08c56ef0bd2d.png)

**Comment by TheAssassin** [comment]
I updated the page with a more exhaustive description how to use the existing software to self-update AppImages in a proper way, highlighting potential cavecats. @probonopd please review.

**Comment by TheAssassin** [comment]
For self-updates, users may now either bundle AppImageUpdate and call it with `$APPIMAGE`, or use libappimageupdate directly.
