### ISSUE TITLE
Help integrating libappimageupdate into existing GUIs

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#32]
As we want AppImage(Self)Update to look and feel as native as possible on every application platform, we might prefer to work with existing Qt, Gtk+, Electron, etc. updater projects rather than writing all of these GUIs and integrations (for self-updating) on our own.

![](https://github.com/alex-spataru/QSimpleUpdater/raw/master/etc/screenshots/downloading.png)

Objective is to achieve a user experience roughly similar to the [Sparkle Framework](https://www.npmjs.com/package/electron-updater) for macOS, but using AppImage and binary delta updates, for Linux.

Let's collect a list of promising candidates here.

__Qt__

* https://github.com/alex-spataru/QSimpleUpdater
* https://github.com/Skycoder42/QtAutoUpdater

__Electron__

* https://www.npmjs.com/package/electron-simple-updater
* https://www.npmjs.com/package/electron-installer-appimage
* https://www.npmjs.com/package/electron-updater

__Python__

* https://github.com/google/omaha (Google Updater)

__Windows__

* https://houbysoft.com/libhul/

__Cross-platform__

* https://github.com/Mendeley/Update-Installer

**Comment by TheAssassin** [comment]
@probonopd I think the current Qt UI is good, usability wise. Minimalist, efficient, not bloated with features. I was using the screenshot you provided here, and extended it with the "Details" widget. Closing here for now. For Gtk+ etc., we'll see whether we want to provide a "standard widget" at all.
