### ISSUE TITLE
"Could not find update information in the AppImage" despite it being there

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#33]
```
me@host:~$ Downloads/linuxdeployqt-continuous-x86_64.AppImage --appimage-updateinformation
gh-releases-zsync|probonopd|linuxdeployqt|latest|linuxdeployqt-_*-x86_64.AppImage.zsync
me@host:~$ Downloads/AppImageUpdate-x86_64.AppImage Downloads/linuxdeployqt-continuous-x86_64.AppImage 
AppImageUpdate version 1-alpha (commit 513949c), build 108 built on 2017-11-04 00:22:04 UTC
Checking for updates...
Could not find update information in the AppImage! Please contact the author to embed update information!
```

**Comment by TheAssassin** [comment]
Can reproduce this with the latest linuxdeployqt build.

According to `objdump`, the update information is embedded at position `0x16af7` (= `92919`), with a length of `0x400` (= `1024`).

```
27 .upd_info     00000400  0000000000000000  0000000000000000  00016af7  2**0
```

AppImageUpdate reads those values correctly from a call to `objdump`.

The commands

```
dd if=linuxdeployqt-continuous-x86_64.AppImage skip=92919 bs=1 count=1024
dd if=linuxdeployqt-continuous-x86_64.AppImage skip=92919 bs=1 count=1024 | wc -c
```

confirm AppImageUpdate's calculation, there's 1024 `\0` characters at this position.

So, I wouldn't blame AppImageUpdate here, as its calculations seem to be correct. I'd suspect the issue to be inside code appimagetool and the AppImage runtime share.

**Comment by probonopd** [comment]
> Can reproduce this with the latest linuxdeployqt build.

The latest build indeed lost the updateinformation probably caused by https://github.com/AppImage/AppImageKit/commit/487771b244892c8eed88326e037ba819041b46f4

Once that is fixed, let's check again.

**Comment by TheAssassin** [comment]
I don't enjoy it, but I told you that this is a bit too automagic. We should think about reverting those changes, I guess. Things are broken, and you always underline that if something breaks the functionality, it should be reverted immediately.

**Comment by TheAssassin** [comment]
P.S.: You should add those new features to the appimagetool test script to make sure things work as intended. This is the perfect example.

**Comment by probonopd** [comment]
Already reverted the suspected offending commit in https://github.com/AppImage/AppImageKit/commit/d8f298fc38cab585166fca09f6fe2658bbce36d7

**Comment by probonopd** [comment]
> I don't enjoy it, but I told you that this is a bit too automagic. We should think about reverting those changes, I guess. Things are broken, and you always underline that if something breaks the functionality, it should be reverted immediately.

That should be addressed by https://github.com/AppImage/AppImageKit/commit/ad47057ba7e228f7d68d016e3fe9379190de5c9b

**Comment by probonopd** [comment]
Issue persists:

```
wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
chmod +x linuxdeployqt-continuous-x86_64.AppImage 
./linuxdeployqt-continuous-x86_64.AppImage --appimage-version
Version: continuous-1-gad47057
./linuxdeployqt-continuous-x86_64.AppImage --appimage-updateinformation
gh-releases-zsync|probonopd|linuxdeployqt|latest|linuxdeployqt-_*-x86_64.AppImage.zsync
wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/AppImageUpdate-x86_64.AppImage
chmod +x AppImageUpdate-x86_64.AppImage 
./AppImageUpdate-x86_64.AppImage ./linuxdeployqt-continuous-x86_64.AppImage 
AppImageUpdate version 1-alpha (commit 513949c), build 108 built on 2017-11-04 00:22:04 UTC
Checking for updates...
Could not find update information in the AppImage! Please contact the author to embed update information!
```

**Comment by TheAssassin** [comment]
Can't reproduce locally any more with the latest linuxdeployqt. Before, there was no actual update information embedded.

However, the latest release build seems to still produce the error. I've pushed an adjustment to the code recently (allocating the memory for the update information string with the right size instead of hardcoding 2kB) which isn't directly related to the issue as linuxdeployqt's update information isn't that large. I can only suspect that the build is broken.

**Comment by probonopd** [comment]
Please test with the build artefacts on GitHub Releases and my bash commands above, thanks.

**Comment by TheAssassin** [comment]
```
> build/appimageupdatetool -d linuxdeployqt-continuous-x86_64.AppImage 
Parsing file: linuxdeployqt-continuous-x86_64.AppImage
AppImage type: 2
Raw update information: gh-releases-zsync|probonopd|linuxdeployqt|continuous|linuxdeployqt*-x86_64.AppImage.zsync
Update information type: ZSync via GitHub Releases
Assembled ZSync URL: https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage.zsync
```

Seems to work. Update check works fine, too:

```
Checking for updates...
Fetching release information for tag "continuous" from GitHub API.
... done!
Update not required, exiting.
```
