### ISSUE TITLE
Says I have the latest version, but I don't

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#35]
```
me@host:~$ ./OldImageMagick-git.7a48608-x86_64.AppImage --appimage-updateinformation
gh-releases-zsync|probonopd|ImageMagick|continuous|ImageMagick*-x86_64.AppImage.zsync
```

AppImageUpdate version 1-alpha (commit 48d9713), build 119 built on 2017-11-07 02:37:53 UTC says that I already have the latest version, except that it isn't:

![_screenshot_2017-11-07_18-53-20](https://user-images.githubusercontent.com/2480569/32509211-f59b0160-c3ec-11e7-996b-7a64beb994a8.png)

(Zipped for GitHub Issues)
[OldImageMagick-git.7a48608-x86_64.AppImage.zip](https://github.com/AppImage/AppImageUpdate/files/1451080/OldImageMagick-git.7a48608-x86_64.AppImage.zip)

**Comment by TheAssassin** [comment]
In this case, the files are equal content wise, but the filenames on the server and locally differ.
As discussed elsewhere, AppImageUpdate should issue a warning whenever the filename on the server changed.

**Comment by probonopd** [comment]
AppImageUpdate behavior has since changed (in positive ways), hence closing here. Thanks!
