### ISSUE TITLE
AppImageUpdate icon missing

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#38]
![icon](https://user-images.githubusercontent.com/2480569/32697065-addd6cac-c787-11e7-8d12-3da237e86798.png)

AppImage contains:

```
me@host:~$ find /tmp/.mount_AppImaZ67Gwk/ | grep icons
(...)
/tmp/.mount_AppImaZ67Gwk/usr/share/icons/hicolor/scalable/AppImage.svg
```

Desktop file says:
```
me@host:~$ cat /tmp/.mount_AppImaZ67Gwk/AppImageUpdate.desktop 
[Desktop Entry]
Name=AppImageUpdate
Type=Application
Icon=AppImage
Exec=AppImageUpdate
```

Probably need to set the [_NET_WM_ICON](https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html#id3076996) property of toplevel window? In Qt, `QApplication::setWindowIcon()` is known to do the trick.

**Comment by probonopd** [comment]
This is also shown in the FLTK documentation, notice the missing icon in the upper left:

![](http://www.fltk.org/doc-1.3/Fl_Native_File_Chooser.png)

**Comment by probonopd** [comment]
Possily we need to use http://www.fltk.org/doc-1.3/classFl__Window.html#a508f3acd43f9b365d35897b5ec197dbe

**Comment by TheAssassin** [comment]
I am not aware of any option to set an icon for a native file chooser. I looked it up, and couldn't find anything for the native one, but the non-native implementation seems to support it. However, the native one looks way better, and I don't think this is really a bug, it's more of a "nice to have" feature.

The icon is also missing in the main application window. I'm going to fix that as soon as possible.

**Comment by probonopd** [comment]
On Ubuntu 17.10, getting with 84e3b3d:

```
me@host:~$ chmod +x AppImageUpdate-84e3b3d-x86_64.AppImage 
me@host:~$ ./AppImageUpdate-84e3b3d-x86_64.AppImage 
./AppImageUpdate-84e3b3d-x86_64.AppImage: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

**Comment by TheAssassin** [comment]
That library might be pulled in by the new `fltk_images` build dependency. I'm not sure why it isn't bundled.

**Comment by probonopd** [comment]
Still in 6555252:

```
me@host:~$ /home/me/AppImageUpdate-6555252-x86_64.AppImage: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

**Comment by TheAssassin** [comment]
Will debug as soon as possible.

**Comment by TheAssassin** [comment]
My local builds link to libpng as well. I don't know what causes linuxdeployqt not to see the dependency and bundle the library. Strange problem, indeed.

**Comment by TheAssassin** [comment]
A bunch of other libraries are missing as well. The majority are dependencies of libcurl (need to bundle my [custom build from OBS](https://build.opensuse.org/package/show/home:TheAssassin:AppImageLibraries/curl-httponly) as soon as possible), but a few other libraries like libjpeg, libXpm etc. should've been bundled.

**Comment by TheAssassin** [comment]
See https://travis-ci.org/AppImage/AppImageUpdate/#L1965-L1966

I have to add `=` signs for the `-executable` parameters as specified here:
```
Options:
...
   -executable=<path>  : Let the given executable use the deployed libraries too
```
https://github.com/probonopd/linuxdeployqt#usage

**Comment by TheAssassin** [comment]
Library issues have been fixed in 352e751.

**Comment by TheAssassin** [comment]
Works.

**Comment by probonopd** [comment]
At least in Deepin Linux it is not working:

![deepinbildschirmfoto20171113074252](https://user-images.githubusercontent.com/2480569/32712712-5587ec8e-c846-11e7-8fc7-80f625d87d2a.png)

That glaring gaop there is AppImageUpdate.
But this has lower priority for now.

**Comment by TheAssassin** [comment]
@probonopd that might be another Linux Desktop Platform Issue. FLTK docs mention you need to load a WM specific icon format. I load XPM now, which seems to be the format for most DEs. If you find out what format is needed for Deepin, I'll add something about it to libDE.

**Comment by probonopd** [comment]
@TheAssassin unfortunately I get the same result in Ubuntu 17.10. 
`png` or `svg` should work everywhere, xpm is the worst of the formats and imho legacy.

![ubuntu1710](https://user-images.githubusercontent.com/2480569/32738264-a9446072-c89c-11e7-8114-e1e0b766c31a.png)

**Comment by probonopd** [comment]
I think I found the reason:

`usr/share/icons/hicolor/scalable/AppImage.svg` needs to be `usr/share/icons/hicolor/scalable/apps/AppImage.svg`, `apps` is missing...

**Comment by probonopd** [comment]
Trying to fix in https://github.com/AppImage/AppImageUpdate/commit/7a1358b705578073d2f921ac613fa00319834e5f

(name is wrong - I meant #38 not #18)

**Comment by TheAssassin** [comment]
> I think I found the reason:
> 
> usr/share/icons/hicolor/scalable/AppImage.svg needs to be
> usr/share/icons/hicolor/scalable/apps/AppImage.svg, apps is missing...

This doesn't have anything to do with it. The `.desktop` file doesn't specify what icon is sent to the WM, the application decides what it sends to X11. See https://github.com/AppImage/AppImageUpdate/blob/rewrite/src/gui_main.cpp#L155-L172. You can't just call `window.icon` with PNG file contents. But I'm not even sure whether the XPM code is 100% right, I haven't really tested that too much in detail. I found it works fine on my xubuntu 16.04 desktop, just tested with 7a1358b.

**Comment by TheAssassin** [comment]
Window icon works fine, but there is no icon in the task bar on Kubuntu 17.10. Strange.

**Comment by TheAssassin** [comment]
@probonopd could you try whether the issue has been resolved with the Qt version?

**Comment by TheAssassin** [comment]
Closing for now. Feel free to reopen, and please attach a screenshot and the OS and version you found this to be an issue on.
