### ISSUE TITLE
Move permissions logic from GUI to libzsync2

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#39]
Move permissions logic from GUI to `libappimageupdate` so that users of the library don't have to deal with this in their own code:

https://github.com/AppImage/AppImageUpdate/blob/0f51e5c4aee19b3db651bd69cfb41c3b7b67f4ae/src/gui_main.cpp#L323-L331

**Comment by TheAssassin** [comment]
How would you imagine this feature? More like a `copyPerms(oldFile, newFile)`, or should that happen automatically?

**Comment by probonopd** [comment]
Automatically.

**Comment by TheAssassin** [comment]
Related to #31.

**Comment by TheAssassin** [comment]
Moving issue to zsync2: https://github.com/TheAssassin/zsync2/issues/11.
