### ISSUE TITLE
Tries to make wrong file executable

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageUpdate#4]
AppImageUpdate works for non-executable AppImages, which is fine, but when you press Launch, also non-executable files are run. That's some kind of odd behavior, it should be changed to either changing the permissions of the AppImage so that the executable bit is set (I'd prefer this way) or showing an error message if it is not executable (the safer way).

**Comment by probonopd** [comment]
Ideally it should show a message and ask the user whether to make it executable and run.

**Comment by probonopd** [comment]
There is a bug that tries to chmod a+x the wrong file, namely based on the name of the .zsync file rather than based on the real name of the file (as contained in the header of the .zsync file):

```
#################### 100.0% 1264.8 kBps DONE    
100 percent

verifying download...checksum matches OK
used 1886208 local, fetched 3931288
chmod: cannot access 'hexchat-latest-x86_64.AppImage': No such file or directory
```

"latest" is wrong here.

**Comment by TheAssassin** [comment]
Fixed in the rewrite.
