### ISSUE TITLE
Add method to read total file size of update from .zsync file

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageUpdate#40]
Required for @probonopd's UI proposal in https://github.com/opendesktop/ocsstore/issues/8#issuecomment-340486795 (second screenshot) to work.

It should be possible to query the total file size of the new file to be queried using the Updater API. This is fairly easy to implement, and, in combination with the `updater.progress()` method, allows for displaying the amount of data that is available locally and/or has been downloaded already.

**Comment by TheAssassin** [comment]
At the moment, the `.zsync` file's contents are not cached. This is not a problem at the moment, the file is downloaded once for every update check (performed only once), and while running an update. For the actual update, that shouldn't be a problem either. However when requesting the value before performing an update, and in the rare case that the remote file is updated between requesting the value and running the update (yes, I know, that's probably quite rare, but might occur regularly with projects where builds are running frequently due to many commits being made), the values might differ, hence making the progress indication imprecise.

Therefore, the `.zsync` file contents should either be cached by whatever is occurs first (running the update or requesting the file size), or, alternatively, the method should be written in the error handling style established in the rest of the library, and return `false` until the value is available (i.e., the update has been started, and the `.zsync` file has been parsed). The latter could be extended to caching the value of an update check as well, and furthermore, the `.zsync` file could be downloaded and the value populated before either an update check is performed or the update is started.

**Comment by probonopd** [comment]
Are you talking about showing the size of the update download (the size of the delta) _prior to having started the update process__? If this proves cumbersome in the zsync architecture (which it probably is) then we should not do that and only show the download filesize once the updating process has started, at least for now.

**Comment by TheAssassin** [comment]
I decided what to do: the value will be available as soon as the update process itself has downloaded the `.zsync` file for its purposes, prior to that, the value won't be available, similar to the progress bar.

**Comment by probonopd** [comment]
The zsync file can't contain the information how much data  _really_ needs to be downloaded, since it's the same zsync file for all users whereas the size of the download is highly dependent on what the user already has available locally. So The total amount of data will only be available shortly before the download starts. What we could show, _in addiition_, though, is the _total filesize on disk_ of the file after the update.

**Comment by TheAssassin** [comment]
Implemented in f866563.
