### ISSUE TITLE
Add Travis build ID to AppImage filenames

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageUpdate#46]
I think it might make sense to add the travis build ID, a monotonically increasing unsigned integer, to the AppImage filenames. This would allow users to see which binary is newer by comparing those numbers by size, which is something the Git commit hash doesn't provide.

CC @probonopd.

The result of this discussion will be applied to linuxdeployqt's and AppImageKit's AppImage releases, too.

**Comment by probonopd** [comment]
While I think that having a monotonically increasing number easily visible would definitely be extremely useful, we should keep in mind that hundreds of projects are using direct permalinks to the continuous builds of appimagetool and linxudeployqt as part of their build pipelines.

So I think it may be good for other applications but not for these. Open for discussion though.
The ideal solution imho would be to have a generic URL without a version number that would redirect to the download that includes a version number, as it is implemented for AppImages on OBS. But I doubt we can convince GitHub to make that happen anytime soon.

So at the minimum, we need to find a solution that doesn't break the hundreds of existing continuous builds using our tools.

**Comment by TheAssassin** [comment]
Yes, that's right, and I worried about that, too. You confirmed my worries.

But as you requested, I'll add the build ID to the `--version` flag code I'm soon going to port to linuxdeployqt/AppImageKit.
