### ISSUE TITLE
Funny characters inside the progress bar

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#47]
There are funny characters inside the progress bar

![funny](https://user-images.githubusercontent.com/2480569/32960559-9a3452aa-cbc5-11e7-92de-1107edce9c09.png)

Also, the GUI would look a bit less "alien" if the progress bar was not yellow but e.g., grey.

**Comment by TheAssassin** [comment]
I've had that bug here, too, on my xubuntu desktop. I am not entirely sure why this happens.

**Comment by TheAssassin** [comment]
Looks like it's some library that breaks this, because local builds work fine. @probonopd what OS did you use?

**Comment by probonopd** [comment]
The above was on Ubuntu 17.10 but I have seen this on other OSes as well.

**Comment by TheAssassin** [comment]
Yeah, as said before, it's probably one of the bundled libraries that breaks it. Can you try compiling AppImageUpdate from source, please?

**Comment by probonopd** [comment]
As a quick (and for me sufficient) fix, don't write _anything_ in the progress bar?

**Comment by TheAssassin** [comment]
Closing as the FLTK UI will be replaced by some other framework.
