### ISSUE TITLE
Fails on type-1 AppImages without embedded magic bytes

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#49]
```
me@host:~$ xxd /isodevice/Applications/Audacity-2.0.5.glibc2.15-x86_64.AppImage | head -n 1
00000000: 7f45 4c46 0201 0100 0000 0000 0000 0000  .ELF............

me@host:~$ strings /isodevice/Applications/Audacity-2.0.5.glibc2.15-x86_64.AppImage | grep CD001
CD001
```

As per the AppImageSpec, this is a valid type-1 AppImage (as is any ISO9660 file that is a Linux ELF file at the same time).

Nevertheless, AppImageUpdate fails:

```
me@host:~$ Downloads/AppImageUpdate-164-6e435c2-x86_64.AppImage /isodevice/Applications/Audacity-2.0.5.glibc2.15-x86_64.AppImage 
AppImageUpdate version 1-alpha (commit 6e435c2), build 164 built on 2017-11-21 11:07:44 UTC
Checking for updates...
Invalid magic bytes: 00
Parsing AppImage failed. See previous message for details. Are you sure the file is an AppImage?
```

**Comment by TheAssassin** [comment]
@probonopd well, the detection logic relies on them to be there. Is there any example code to "detect" whether something is a valid type 1 AppImage? Do I have to test for the ELF header and the ISO9660? 

Should I take any non-2 file as a type 1 AppImage? I've read these "guessing type 1" lines from time to time.

**Comment by probonopd** [comment]
String "ELF" at offset 1 __and__ string "CD001" at  offset 32769 = type-1 AppImage.

**Comment by TheAssassin** [comment]
@probonopd please try the next build with your AppImage. It detects type 1 based on the method you described. For the Audacity AppImage you tried specifically, update information seems to be lacking though.

**Comment by probonopd** [comment]
Yes, works as intended now. Thank you!

```
me@host:~$ Downloads/AppImageUpdate-169-6ed6b6b-x86_64.AppImage Downloads/Audacity-2.0.5.glibc2.15-x86_64.AppImage 
AppImageUpdate version 1-alpha (commit 6ed6b6b), build 169 built on 2017-11-25 01:42:31 UTC
Checking for updates...
Invalid magic bytes: 00
Guessing AppImage type 1
Could not find update information in the AppImage. Please contact the author of the AppImage and ask him to embed update information.
```
