### ISSUE TITLE
appimageupdatetool does not work in systems without objdump

### ISSUE THREAD

**Issue by shacknetisp** [AppImage/AppImageUpdate#51]
Using the tool as `appimageupdatetool.AppImage <some appimage>` without objdump installed results in the following output:
```
Checking for updates...
sh: 1: objdump: not found
```
and an indefinite hang.

**Comment by probonopd** [comment]
Please install `objdump` from your distribution.

**Comment by probonopd** [comment]
Actually, it _should__ be bundled:

https://github.com/AppImage/AppImageUpdate/blob/65b152ef3c5737aa7bea24ccd350556482a5656d/resources/build-appimages.sh#L45

@TheAssassin please check

**Comment by TheAssassin** [comment]
@shacknetisp without telling us the version of appimageupdatetool and what OS you use, it's pretty impossible to debug this. You need to provide additional information. As @probonopd said, for quite some time, AppImageUpdate AppImages bundle objdump, so you're probably using an outdated version.
I'm kind of surprised you experience this specific issue.

The infinite hang shouldn't happen however. But that's another issue.

**Comment by shacknetisp** [comment]
The version is the latest in the release at time of writing, `AppImageUpdate-167-65b152e-x86_64.AppImage`

Operating Systems I tested were Ubuntu 16.04 (binutils were installed, but I reproduced the error when temporarily removing objdump) and Porteus XFCE 3.2.2 without binutils installed.

I made sure the appimageupdatetool included objdump by checking the `squashfs-root/usr/bin/` directory resulting from `--appimage-extract` before reporting.

**Comment by probonopd** [comment]
@TheAssassin you are aware that there is no AppRun which would set the `$PATH` to include `usr/bin`?

**Comment by TheAssassin** [comment]
That means the bundled version isn't used. And I'm pretty certain I know why. I'll have to add some logic to call the bundled `objdump` specifically when running within an AppImage, and otherwise call the system wide (for development).

**Comment by probonopd** [comment]
...or, even better, use my `elf.c`

**Comment by TheAssassin** [comment]
I'm quick fixing it for now by adding those pieces. I'll make this change eventually.

**Comment by TheAssassin** [comment]
@shacknetisp please retry with the latest version. Quickly tested insinde some fresh containers without a system wide objdump, works fine.

**Comment by shacknetisp** [comment]
The issue has been corrected, thank you.

**Comment by TheAssassin** [comment]
You're welcome. Additional testers are always a plus.

By the way, since you might be interested in it, the self updating concept phase is ending in this sprint (ending next Wednesday...?), then we'll have an upstream solution for this. As of now, you can also just use libappimageupdate as-is for a more "native" look and feel. You're invited to keep track of https://github.com/AppImage/AppImageUpdate/issues/30.
