### ISSUE TITLE
`appimageupdatetool-179-30cb1ce-x86_64.AppImage` fails

### ISSUE THREAD

**Issue by KurtPfeifle** [AppImage/AppImageUpdate#55]
I tried to use *`appimageupdatetool-*.AppImage`* from the commandline, but in a very non-standard way:

1. I call it via a symlink named *`aiu-tool`*.
1. I run it against a symlink named *`im`* pointing to the real AppImage of ImageMagick.

It all goes well until about 69%. Then it falls down with a chain of messages saying:

     [....]
    -1 returned
    -1 returned

    zsync2: failed to retrieve from ImageMagick-bc5b257-gcc-x86_64.AppImage, status -1
    100.00% done (19.40 of 19.40 MiB)...
    Update failed!

I'm aware that my AppImage should really carry a proper version information (which it doesn't do this yet) -- but I also like to "kick the tires" in order to test stuff.

The ImageMagick AppImage so far works as expected, even though the Travis build at the end said *"Your build exited with 1."* and I had to "force" the upload to the GitHub releases page.

However, I submit this issue because you may gain interesting insights into your tool when it has to deal with a possibly faulty AppImage.

----

I also ran *`aiu-tool --self-update`* and *`./aiu-tool ./aiu-tool`*, which both worked, despite of using symlinks only.

The updated aiu-tool symlink meanwhile points to *appimageupdatetool-180-d89753f-x86_64.AppImage*, but this also fails on my ImageMagick AppImage. This most likely means that something is wrong with my ImageMagick AppImage and its .zsync file.

----

**Files:**
* My [ImageMagick GitHub releases page](https://github.com/KurtPfeifle/ImageMagick/releases/)
* [ImageMagick-xperimental.AppImage](https://github.com/KurtPfeifle/ImageMagick/releases/download/continuous/ImageMagick-xperimental.AppImage)
* [ImageMagick-bc5b257-gcc-x86_64.AppImage.zsync](https://github.com/KurtPfeifle/ImageMagick/releases/download/continuous/ImageMagick-bc5b257-gcc-x86_64.AppImage.zsync)

**Comment by probonopd** [comment]
The AppImage you are trying to update __from__ (="old") is `ImageMagick-xperimental.AppImage`?

**Comment by KurtPfeifle** [comment]
@probonopd asked:
> *"The AppImage you are trying to update __from__ (="old") is `ImageMagick-xperimental.AppImage`?"*

Yes.

However, and unfortunately, by accident I locally overwrote my previous AppImage and triggered a new Travis run, so the old one is no longer there to narrow down the error. What I have now is the newest, and here *`appimageupdatetool`* (correctly) tells me that there is nothing to update, and it's the newest version. So no way to reproduce the problem (unless you downloaded the AppImage early enough...)

Will have to see if the problem re-appears for the next builds. I'll keep the issue open for now. Will close it if it is gone...

**Comment by probonopd** [comment]
No, I didn't save the old one...

**Comment by TheAssassin** [comment]
> I'm aware that my AppImage should really carry a proper version information (which it doesn't do this yet) -- but I also like to "kick the tires" in order to test stuff

As mentioned a few times, AppImageUpdate doesn't care at all about any version information and alike meta data. What it does is download the descriptor file for the remote file, then check the local file for chunks which haven't been modified, and download the rest. This mechanism is based on the file contents only.

I am not a fan of issues kept open until they can be someday in the future, but I understand your reason to do so. However, I'd ask you to find a way to reproduce this behavior which is independent from such a scenario, a [minimal working example (MWE)](https://stackoverflow.com/help/mcve). This makes tracing down alleged bugs a lot easier for the developers, and also allows for writing reproducible tests.

**Comment by TheAssassin** [comment]
I assume this has been resolved. @KurtPfeifle please confirm.

**Comment by TheAssassin** [comment]
Closing as it has most likely been resolved. Please reopen otherwise.
