### ISSUE TITLE
Implement -h and --help for AppImageUpdate

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#61]
Implement -h and --help for AppImageUpdate. How can I get AppImageUpdate to display the update information of an AppImage?

**Comment by TheAssassin** [comment]
You can't, it's only implemented in the CLI tool. And there *is* a `-h/--help` flag. Did you even try to call it with `-h`? It shows a list of available parameters.

**Comment by TheAssassin** [comment]
```
/tmp> ./AppImageUpdate-185-1c72f3b-x86_64.AppImage --version
AppImageUpdate version 1-alpha (commit 1c72f3b), build 185 built on 2018-01-03 16:41:48 UTC
AppImageUpdate version 1-alpha (commit 1c72f3b), build 185 built on 2018-01-03 16:41:48 UTC
/tmp> ./AppImageUpdate-185-1c72f3b-x86_64.AppImage -h
AppImageUpdate version 1-alpha (commit 1c72f3b), build 185 built on 2018-01-03 16:41:48 UTC
  ./AppImageUpdate-185-1c72f3b-x86_64.AppImage {OPTIONS} []

    AppImageUpdate -- GUI for updating AppImages

  OPTIONS:

      -h, --help
      -V, --version                     Display version and exit.
      -j, --check-for-update            Check for update. Exits with code 1 if
                                        changes are available, 0 if there are
                                        not,other non-zero code in case of
                                        errors.
      --self-update
                                  Path to AppImage that should be updated
      "--" can be used to terminate flag options and force all following
      arguments to be treated as positional options
```
Should fix the strange double version string though, I guess.

**Comment by probonopd** [comment]
I was referring to the AppImageUpdate GUI application. Because I never use the CLI tool.

**Comment by TheAssassin** [comment]
Still, the `help` option is available. If you want this issue to be about adding a feature to AppImageUpdate, please take some time and reword the title. Otherwise, we should close it.

**Comment by probonopd** [comment]
True. Sorry, my fault, I had an outdated version.

**Comment by TheAssassin** [comment]
A tip from my end, AppImageUpdate has a self-update feature.

**Comment by probonopd** [comment]
True. But running itself on itself should get the job done, too ;-)

**Comment by TheAssassin** [comment]
I just figured running it with `--self-update` is a lot easier, because you don't need to specify the path twice.
