### ISSUE TITLE
Segmentation fault when AppImage selected from file explorer.

### ISSUE THREAD

**Issue by antony-jr** [AppImage/AppImageUpdate#63]
This is what I get when I run the AppImageUpdate and then select my AppImage through the file explorer.
```
AppImageUpdate version 1-alpha (commit 1c72f3b), build 185 built on 2018-01-03 16:41:48 UTC
sh: $'@\350\375\001': command not found
Failed to call KDE configuration program @��!
Checking for updates...
Segmentation fault (core dumped)
```

is this intensional ? I'm using the latest build.

**Note**: This error only occurs when I select the AppImage from the gui , It works great ❤️ if I open it through the command line.

**Comment by TheAssassin** [comment]
This is a bug in [libdesktopenvironments](https://github.com/TheAssassin/libdesktopenvironments). Please open an issue there. Thanks!

**Comment by TheAssassin** [comment]
Check out https://github.com/TheAssassin/libdesktopenvironments/issues/3.

**Comment by antony-jr** [comment]
I will be closing this then! 👍

**Comment by TheAssassin** [comment]
I'm really bugged I couldn't help you.
