### ISSUE TITLE
AppImage Update Qt Version is not bundled properly

### ISSUE THREAD

**Issue by antony-jr** [AppImage/AppImageUpdate#70]
Hey!
Just want to tell you that the new Qt version of the AppImage Update did not bundle any qt stuff. Avoid this if it was a build error... 

```
execv error: No such file or directory
```

Contents of the AppImage... /usr/bin/
```
fltk-config  fluid  objdump  zsync2  zsyncmake2
```
```

**Comment by TheAssassin** [comment]
Thanks for the hint. I'll have a look. It's most likely due to a build error, see https://travis-ci.org/AppImage/AppImageUpdate/jobs/343837645#L2896, the binary isn't getting bundled, which does unfortunately not affect the AppImage generation.
