### ISSUE TITLE
libappimageupdate build failed since elf added

### ISSUE THREAD

**Issue by akiraohgaki** [AppImage/AppImageUpdate#78]
Can you check this build log between line 2634 and line 2657?
https://travis-ci.org/opendesktop/ocs-manager/jobs/346324869#L2634

How can I do for this?

**Comment by TheAssassin** [comment]
```
error: 'for' loop initial declarations are only allowed in C99 mode
```

Sorry for the inconvenience. Looks like libappimageupdate needs to compile the ELF stuff in C99 mode. I'll push a fix asap.

**Comment by TheAssassin** [comment]
Please reopen the issue if the fix doesn't work for you.

**Comment by akiraohgaki** [comment]
Build passed! Thanks for the fix.
