### ISSUE TITLE
Full download when local filename differs from the remote one

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/AppImageUpdate#8]
AppImageUpdate tends to completely download a new file from the server when the server's and the local filename don't match.
The problem is that zsync (which is called internally) looks for a file matching `Filename: ` in the `.zsync` file. This is totally fine behavior for "normal" download jobs, but does not work very well with the way we use it.
Thus, we should make sure that `Filename:` matches `argv[1]`, by replacing that (using `sed` or a comparable alternative).

**Comment by probonopd** [comment]
Good catch!

Instead of rewriting the .zsync file we might just as well change this behavior in [zsync-curl](https://github.com/probonopd/zsync-curl), which we had to fork for our purposes anyway.

**Comment by TheAssassin** [comment]
Fixed in #15. Rewrite also doesn't have this issue.
