### ISSUE TITLE
Delete previous version after updating

### ISSUE THREAD

**Issue by Tvax** [AppImage/AppImageUpdate#82]
It could be handier if AppImageUpdate could delete the previous version of the AppImage once it has been updated.

**Comment by TheAssassin** [comment]
@Tvax this used to be the default behavior, but @probonopd requested to preserve the old AppImage by default. That's why I introduced the options `-O` and `-r` for appimageupdatetool (the UI, AppImageUpdate, doesn't have them yet, but it's planned).

**Comment by Tvax** [comment]
OK, if so I'm gonna use this options, whatsoever I'm looking forward to see this option in the UI. Great job even though!

**Comment by TheAssassin** [comment]
@Tvax thanks for bringing this up again, though. I'll put it near the top on my TODO list.

**Comment by probonopd** [comment]
> It could be handier if AppImageUpdate could delete the previous version of the AppImage once it has been updated.

@Tvax a big advantage of AppImage over traditional packaging formats is that you can have multiple versions in parallel. So if you update to the new version, you can test it and only after you are fully convinced of the new version, you may choose to delete the old version.
