### ISSUE TITLE
Provide a Qt library that asks the user whether to check for updates

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#86]
User story:

As a Qt application developer, I want to include something into my code and/or AppImage that asks the user whether the application should search for updates. I don't want to have to code that myself. Possibly I am already using https://sparkle-project.org/ on the Mac which handles this kind of thing automatically.

Ideally, please __don't__ ask the user whether the application should search for updates directly when the application is launched for the first time. This gives a bad impression. Usually people want to look at the application when it is launched for the first time, and an update nag screen just gets in their way. Also, automatic screenshots for AppImageHub are not giving the best impression when all they show is an update nag screen. At least do this only on the _second_ launch of the application, or when the user _quits_ the application. See what Sparkle does; it is usually good at this (not bringing up an update nag screen directly after you downloaded an application and have launched it for the first time).

**Comment by TheAssassin** [comment]
There is such a library: `libappimageupdate-qt`. It provides an update check that you can run, and when there's an update, you can `show()` the UI, which will perform the update. So, you as a developer decide the workflow.

**Comment by antony-jr** [comment]
We **don't** really have to block the application on startup , We just have to run the updater in a seperate thread(Hidden) and if any updates are available provide them with a window like **sparkle framework**.
This way the application just works without the annoying checking for updates message.

**Comment by probonopd** [comment]
Wouldn't it be nice if there was a generic way to do this so that not every developer needs to think about when to show what?

Point in case:
https://github.com/AppImage/appimage.github.io/blob/efb54b0839635399843b81ae6be08fb027ca8986/database/Pext/screenshot.png

**Comment by antony-jr** [comment]
@probonopd you are right!

**Comment by antony-jr** [comment]
@probonopd here is a prototype ( I've been working on the same issue )... 
![Imgur](https://i.imgur.com/k6zsDYO.png)

But to enable updates , you just have to execute...

```
 $ osutoolkit YourApp.AppImage -o UpdatableAppImage.AppImage
```

**Comment by TheAssassin** [comment]
@antony-jr you are right, there is a need for a better API for libappimageupdate-qt. But this issue was requesting such a library at all. I closed it since it there _is_ such a library. Suggestions for improvements should go into another issue.

**Comment by probonopd** [comment]
Sorry if I was not clear, I meant to describe _what_ that library should do ;-)
