### ISSUE TITLE
CLI tool as large as GUI application

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#87]
The CLI tool is as large as GUI application, why? Must be a bug?

![screenshot from 2018-04-10 18-06-46](https://user-images.githubusercontent.com/2480569/38568880-4ffb3200-3cd9-11e8-9263-8e2843cd12a9.png)

**Comment by TheAssassin** [comment]
This happens from time to time, due to me trying to use the ignore list feature I introduced in https://github.com/AppImage/AppImageKit//pull/436 to use the same AppDir for two AppImages.
To fix this permanently, we just need to use two AppDirs.
