### ISSUE TITLE
Releases need consistent names

### ISSUE THREAD

**Issue by TheLastProject** [AppImage/AppImageUpdate#89]
Scripts needing to get the latest version of AppImageUpdate or appimageupdatetool cannot reliably due so, because the URLs in Releases change each build. These should be made consistent, or at least there should be a link available that always redirects to the right place.

**Comment by TheAssassin** [comment]
CC @probonopd 

I could imagine to introduce consistent file names for appimageupdatetool. It seems like users depend on it, and use it in scripts.
Regarding AppImageUpdate, I like the versioned filenames. Users like the ability to see what version of an app they have from its filename.

@TheLastProject do you need AppImageUpdate, too, or just appimageupdatetool?

**Comment by TheLastProject** [comment]
Currently I seem to get along fine with a git clone and manual build of AppImageUpdate.

**Comment by TheAssassin** [comment]
@TheLastProject I was referring to the filenames. Do you think we need to change the naming of AppImageUpdate (UI app), too?

**Comment by TheLastProject** [comment]
For consistency I'd probably change both, but I haven't personally had the need to get the AppImageUpdate AppImage in a script. However, I obviously don't know what others need.

**Comment by probonopd** [comment]
> Scripts needing to get the latest version of AppImageUpdate or appimageupdatetool cannot reliably due so, because the URLs in Releases change each build.

We talked about this and came to the conclusion that artefacts used for _producing_ AppImages should be reachable under constant URLs, while this is not needed for artefacts for _consuming_ AppImages (such as the update tools). 

Can you describe a bit more your use case? Would parsing the GitHub API to get the latest continuous release and its download URL be an option?

**Comment by TheAssassin** [comment]
All right. I personally don't mind the change. Let's hear what @probonopd has to say.

**Comment by probonopd** [comment]
Not against it.

**Comment by TheAssassin** [comment]
Actually, when implementing https://github.com/AppImage/AppImageUpdate/issues/88#issuecomment-386826144, we could provide a `.zsync` file with a static filename resolving to a static URL. With it, people could use zsync(2) to download the latest versions of AppImageUpdate.

**Comment by luzpaz** [comment]
>  With it, people could use zsync(2) to download the latest versions of AppImageUpdate.

@TheAssassin can you elaborate on how this works? what is `zsynch(2)` ?

**Comment by TheAssassin** [comment]
They contain all information needed to delta-update an AppImage. See https://docs.appimage.org/packaging-guide/optional/updates.html?highlight=zsync, https://github.com/AppImage/zsync2.
