### ISSUE TITLE
Make it possible to only compile libappimageupdate without the need for Qt

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#93]
This is a sister ticket to https://github.com/AppImage/AppImageKit/issues/798.

Please make it possible to only compile libappimageupdate with minimal dependencies being downloaded and needed by CMake.

Use case:
I as a developer want to use libappimageupdate in my project. I don't care about the Qt GUI, nor tests. I just want to consume libappimageupdate, using as few build-time dependencies as possible, and for those that are neeeded, use as many distro-provided ones as possible. (To increase chances of anything that uses libappimageupdate to ever be packaged in distros.)

Currently I am getting

```
 Could not find a package configuration file provided by "Qt5" with any of
  the following names:
    Qt5Config.cmake
    qt5-config.cmake
```

https://travis-ci.org/probonopd/gs-plugin-appimage/builds/386428695#L2578-L2582

**Comment by TheAssassin** [comment]
You already compiled AppImageUpdate at some point without Qt. Just add `-DBUILD_QT_UI=OFF` to your CMake command line.

Perhaps this should go into the README.

**Comment by probonopd** [comment]
Would it be possible to have 2 separate directories, one for libappimageupdate (which needs to be built  first) and then a completely separate one containing AppImageUpdate and appimageupdatetool (which needs the other one built first)? Two completely decoupled CMake systems. So people who are only interested in the library would just build the former but not the latter.

**Comment by TheAssassin** [comment]
This adds a significant amount of maintenance overhead.

**Comment by probonopd** [comment]
OK, I don't know how distro packagers will think about this, but we'll see. cc @Conan-Kudo

**Comment by Conan-Kudo** [comment]
I'd actually rather build everything, after all, we can just subpackage out each built component so that at install time, you don't need everything.

**Comment by TheAssassin** [comment]
> So people who are only interested in the library would just build the former but not the latter.

Again: you don't have to _build_ what you don't need if you include the entire CMake project. But you have to make the platform checks happy. There's a huge difference between building and configuring.
