### ISSUE TITLE
libappimageupdate Updater doesn't work when overwrite is true

### ISSUE THREAD

**Issue by pkwong4321** [AppImage/AppImageUpdate#96]
hi,
i initialized Updater with Updater("/home/user/app/app.AppImage", true)
but when i do updater.start()
console have the following log:
Updating from generic server via ZSync
zsync2: Target file: /home/user/app//home/user/app/app.AppImage

**Comment by pkwong4321** [comment]
`    auto updater = new appimage::update::Updater("/home/patrick/testing.AppImage", true);
    updater->start();
    while (!updater->isDone()) {
        std::string nextMessage;
        while (updater->nextStatusMessage(nextMessage)) {
            printf(nextMessage.c_str());
        }
    }`

the first message prints
zsync2: Target file: /home/patrick//home/patrick/testing.AppImage

**Comment by pkwong4321** [comment]
Sorry for late replies, here's the info
Debian Stretch / Ubuntu 16.04
gcc 6.3.0 / gcc 5.3.1
both are using ext4

**Comment by TheAssassin** [comment]
Have you tried the zsync2 AppImages directly? If this is a bug in libzsync2, we should debug it there directly.
Also, did you try appimageupdatetool with `-O`?

**Comment by pkwong4321** [comment]
yes, it's reproducible
this works:
appimageupdatetool-365-db93246-x86_64.AppImage -O testing.AppImage
this doesn't:
appimageupdatetool-365-db93246-x86_64.AppImage -O /home/patrick//home/patrick/testing.AppImage

**Comment by TheAssassin** [comment]
So the issue you have is because of the absolute path, and only when overwriting is enabled? That's quite odd.

I tested with relative paths only, so that's quite a good catch. I'll try with an absolute path myself later. Meanwhile, could you please check whether absolute paths work without `-O` with appimageupdatetool?

**Comment by pkwong4321** [comment]
yes, it works. The problem only happens when overwriting is enabled

i tried commenting zsync2's applyCwdToPathToLocalFile in zsclient.cpp line 739
then it'll work, but i'm sure that code is there for a reason...

**Comment by TheAssassin** [comment]
Fixed accidentally in https://github.com/AppImage/AppImageUpdate/commit/e5fdf719bfe7d65c68358a313cb701a483f779b1.
