### ISSUE TITLE
Do not hard-depend on gpg2

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#97]
* Download https://bintray.com/probono/AppImages/download_file?file_path=Linux_Tycoon_in_DOSBox-0.74.glibc2.14-x86_64.AppImage
* Try to update it

![](https://user-images.githubusercontent.com/2480569/43331308-fd615480-91b4-11e8-84b0-aa68348b2356.png)

**Comment by TheAssassin** [comment]
"Works fine on my machine", unfortunately. Could you please check your commandline for the `gpg2` output?

**Comment by TheAssassin** [comment]
Does it work though if you install `gnugp2`? (I wonder why it's missing _anyway_, Ubuntu uses it internally to verify apt package integrity...)

Skipping is a bad idea. Instead, I'd rather return a "warning" state (i.e., make the progress bar yellow, and ask for installing `gpg2`. Also, we should think about supporting `gpg` v.1 as a fallback.

**Comment by probonopd** [comment]
`gpg` is installed.

**Comment by probonopd** [comment]
When I install `gpg2`:

```
me@host:~$ '/home/me/Downloads/AppImageUpdate-362-84cdbe6-x86_64.AppImage' '/home/me/Downloads/Linux_Tycoon_in_DOSBox-0.74.glibc2.14-x86_64.AppImage' 
AppImageUpdate version 1-alpha (commit 84cdbe6), build 362 built on 2018-07-26 20:33:21 UTC
Updating from Bintray via ZSync
zsync2: /home/me/Downloads/Linux_Tycoon_in_DOSBox-0.74.glibc2.14-x86_64.AppImage found, using as seed file
zsync2: Target file: /home/me/Downloads/Linux_Tycoon_in_DOSBox-0.74.glibc2.14-x86_64.AppImage
zsync2: Reading seed file: /home/me/Downloads/Linux_Tycoon_in_DOSBox-0.74.glibc2.14-x86_64.AppImage
zsync2: Usable data from seed files: 100.000000%
zsync2: Renaming temp file
zsync2: Fetching remaining blocks
zsync2: Verifying downloaded file
zsync2: checksum matches OK
zsync2: used 3897344 local, fetched 0
Segmentation fault
```

**Comment by probonopd** [comment]
> "Works fine on my machine"

https://docs.appimage.org/packaging-guide/testing.html

;-)

**Comment by TheAssassin** [comment]
That's quite strange... I'll have a look at the segfault first, then will take care of the hard dependency.

**Comment by probonopd** [comment]
After I do `sudo apt install gnupg2` it works without segfaults.

**Comment by probonopd** [comment]
After installing and uninstalling various `*gpg*` packages, I cannot really reproduce the segfault anymore...

**Comment by TheAssassin** [comment]
Interesting. Anyway, a check whether the program exists before trying to validate signatures is a good idea.

**Comment by probonopd** [comment]
Yes, and _not depend on it_ (or bundle it).

**Comment by TheAssassin** [comment]
That's what I meant, actually. See https://github.com/AppImage/AppImageUpdate/issues/97#issuecomment-408486632

**Comment by TheAssassin** [comment]
I already implemented a check for that purpose. See https://github.com/AppImage/AppImageUpdate/blob/55f58318664772aeb5a8135e3a152d38ed082b9b/src/updater.cpp#L887.

I will move this from errors to warnings, that should fix the issue.

**Comment by TheAssassin** [comment]
![screenshot_2018-07-27_21-01-20](https://user-images.githubusercontent.com/4503202/43341587-450dd06c-91e0-11e8-8ea1-7f959aca46f5.png)
